namespace: gamefeed

image:
  registry: battulalaxmankumar04
  tag: latest
  pullPolicy: Always

postgres:
  enabled: true
  image: postgres:16-alpine
  serviceName: postgres-db
  port: 5432
  user: postgres
  password: postgres
  database: postgres
  storage: 5Gi
  initdb:
    enabled: true
    script: |
      #!/bin/bash
      set -e
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE user_db;
        CREATE DATABASE game_db;
        CREATE DATABASE review_db;
        CREATE DATABASE comment_db;
      EOSQL

jwtSecret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"

services:
  user-service:
    imageName: user-service
    replicas: 1
    port: 8081
    serviceType: ClusterIP
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: dummy

  game-service:
    imageName: game-service
    replicas: 1
    port: 8082
    serviceType: ClusterIP
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/game_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  review-service:
    imageName: review-service
    replicas: 1
    port: 8083
    serviceType: ClusterIP
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/review_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  comment-service:
    imageName: comment-service
    replicas: 1
    port: 8084
    serviceType: ClusterIP
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/comment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  api-gateway:
    imageName: api-gateway
    replicas: 1
    port: 8080
    serviceType: NodePort
    nodePort: 30081
    env:
      USER_SERVICE_URL: http://user-service:8081
      GAME_SERVICE_URL: http://game-service:8082
      REVIEW_SERVICE_URL: http://review-service:8083
      COMMENT_SERVICE_URL: http://comment-service:8084

  frontend:
    imageName: frontend
    replicas: 1
    port: 3000
    serviceType: NodePort
    nodePort: 30080
    env: {}

monitoring:
  serviceMonitor:
    enabled: false
    path: /actuator/prometheus
    interval: 15s
