apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/blaxmankumar/fibex.git
    targetRevision: main
    path: gitops/shared
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gamefeed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
