apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/blaxmankumar/fibex.git
    targetRevision: main
    path: gitops/user-service
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gamefeed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
